typography_spectrum: 0.88955083838664
color:
  brandStrength: 0.5679650108795613
  lightness: 0.6112487509381026
  saturation: 0.7516567956190556
  rhythmicContrast: 0.3806840863544494
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
layout_spectrum: 0.48146934318356216
author:
  name: Jan Friman
  email: jan@peopleorg.co
  url: peopleorg.co
name: PeopleOrg
navigation:
  - name: PeopleOrg | Business
    id: 6252a25f-02c9-40a0-983f-3306236283ec
    type: content
  - name: PeopleOrg | People
    id: 52a3f324-9e50-4c67-b5fd-957c279b7ea4
    type: content
title: People Are We
description: Aligning Organizations Digitally
