typography_spectrum: 0.25458204257301986
color:
  brandStrength: 0.5679650108795613
  lightness: 0.6112487509381026
  saturation: 0.7516567956190556
  rhythmicContrast: 0.3806840863544494
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
layout_spectrum: 0.6489341524429619
author:
  name: Jan Friman
  email: jan@peopleorg.co
  url: 'http://flipboard.com/@janfriman'
name: PeopleOrg
title: People Are We
description: Aligning Organizations Digitally
