typography_spectrum: 0.5041110187303275
color:
  brandStrength: 0.1190514147747308
  lightness: 0.5934702870436013
  saturation: 0.11804852937348187
  rhythmicContrast: 0.46039846702478826
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
layout_spectrum: 0.41024322994053364
author:
  name: Jan Friman
  email: jan@peopleorg.co
  url: 'http://flipboard.com/@janfriman'
name: PeopleOrg
navigation:
  - name: Get Invite
    url: 'https://peoplearewe.mightybell.com/'
    type: external
  - name: Open Research
    url: 'http://flip.it/5gb4tt'
    type: external
  - name: The Story
    url: 'http://bit.ly/RekindlingCWHR'
    type: external
title: People Are We
description: Aligning Organizations Digitally
